### ISSUE TITLE
need to include imports-loader in package.json for generated project

### ISSUE THREAD

**Issue by mnebuerquo** [cnatis/generator-mithril-webpack#12]
See [this issue](https://github.com/bline/bootstrap-webpack/issues/5) in bootstrap-webpack. It's the same set of error messages I was getting when building with webpack.

I had to do `npm install --save imports-loader` to fix it. This could have been in package.json from the beginning.

If there's a reason not to include this package, then a note in the readme would be helpful.

Thanks!

**Comment by cnatis** [comment]
imports-loader should be installed, it must have been forgotten when I added bootstrap to the project. Ill fix this ASAP.

**Comment by cnatis** [comment]
I have added the imports-loader to the package.json and updated the npm package to the latest version. Thank you for letting me know @mnebuerquo :)

**Comment by mnebuerquo** [comment]
Thanks for fixing it so fast!
