### ISSUE TITLE
optional dependencies are not saved in package.json

### ISSUE THREAD

**Issue by mnebuerquo** [cnatis/generator-mithril-webpack#13]
I cloned my repo and tried to build my project on another machine. The bootstrap-sass dependencies were not installed by npm on the second instance because they were not in package.json.

I'm not real familiar with Yeoman generators, but  I think the issue is the `npmInstall()` function needs the save option added:

```
@@ -300,10 +300,10 @@ module.exports = yeoman.generators.Base.extend({
                }

                // Install dependencies
-               this.npmInstall(optionalDependencies);
+               this.npmInstall(optionalDependencies, {'save':true} );
                this.installDependencies({
                        npm: true,
                        bower: false
                });
```

Thanks!

**Comment by cnatis** [comment]
Fixed on branch issue13, merged into master. Available in V0.0.9

Thank you for letting me know, sorry it took so long to fix.
